import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createSnapshotProjection } from "../src/core/snapshot-projection.js";
import { buildSnapshotHtml } from "../src/core/snapshot-html.js";
import { toPersistedHole } from "../src/core/schema.js";
import { makeNode } from "../src/core/hole/node.js";
import { toolDefinitions } from "../src/node/mcp/tools.js";
import { getDompurifyScript, getMermaidScript, getUiAssets } from "../src/node/shared/dist-assets.js";
import { FETCH_PROXY_ALLOWED_HOSTS, WEB_CONNECT_SOURCES } from "../policy/origins.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedDirectory = path.join(root, "docs/generated");
const check = process.argv.includes("--check");
const outputs = new Map();

const sourceFiles = await filesUnder("src", (name) => name.endsWith(".js") || name.endsWith(".d.ts"));
const testFiles = await filesUnder("test", (name) => name.endsWith(".test.mjs"));
const protects = await readTestPurposes(testFiles);
const packageJson = JSON.parse(await fs.readFile(path.join(root, "package.json"), "utf8"));
const tokenSource = await fs.readFile(path.join(root, "src/design/tokens.css"), "utf8");

outputs.set("module-map.md", moduleMap(sourceFiles));
outputs.set("test-map.md", testMap(protects));
outputs.set("tokens.md", tokenMap(tokenSource));
outputs.set("env.md", await envMap());
outputs.set("mcp-tools.md", mcpToolMap());
outputs.set("commands.md", commandMap(packageJson.scripts || {}));
outputs.set("csp.md", cspMap());
outputs.set("../tour.html", await buildTour());

const stale = [];
for (const [relativeName, contents] of outputs) {
  const target = path.resolve(generatedDirectory, relativeName);
  if (check) {
    const current = await fs.readFile(target, "utf8").catch(() => null);
    if (current !== contents) stale.push(path.relative(root, target));
  } else {
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, contents, "utf8");
  }
}

if (check) {
  const missingPaths = await scanDocumentPaths();
  if (stale.length || missingPaths.length) {
    if (stale.length) process.stderr.write(`Generated docs are stale:\n${stale.map((name) => `- ${name}`).join("\n")}\n`);
    if (missingPaths.length) process.stderr.write(`Document paths do not exist:\n${missingPaths.map((entry) => `- ${entry}`).join("\n")}\n`);
    process.exit(1);
  }
}

function heading(title) {
  return `<!-- Generated by scripts/build-docs.mjs. Do not edit. -->\n\n# ${title}\n\n`;
}

function moduleMap(files) {
  const groups = new Map();
  for (const file of files) {
    const parts = file.split("/");
    const group = parts.length > 2 ? `${parts[0]}/${parts[1]}` : parts[0];
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group).push(file);
  }
  let out = heading("Module map");
  out += "This inventory is derived from the source tree.\n\n";
  for (const [group, entries] of [...groups].sort(([a], [b]) => a.localeCompare(b))) {
    out += `## ${group}\n\n${entries.map((file) => `- \`${file}\``).join("\n")}\n\n`;
  }
  return out;
}

function testMap(entries) {
  let out = heading("Test map");
  out += "Each description is harvested from the test file's `@protects` declaration.\n\n";
  for (const tier of ["unit", "contracts", "integration", "e2e", "performance", "packaging"]) {
    const matches = entries.filter((entry) => entry.file.startsWith(`test/${tier}/`));
    out += `## ${tier}\n\n`;
    out += matches.length
      ? matches.map(({ file, purpose }) => `- \`${file}\` — ${purpose}`).join("\n") + "\n\n"
      : "_No tests in this tier._\n\n";
  }
  return out;
}

function tokenMap(source) {
  const tokens = [...source.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)]
    .map((match) => ({ name: match[1], value: match[2].trim() }));
  let out = heading("Design tokens");
  out += "Values are read from `src/design/tokens.css`; repeated theme overrides remain visible.\n\n";
  out += "| Token | Value |\n| --- | --- |\n";
  out += tokens.map(({ name, value }) => `| \`${name}\` | \`${value.replace(/\|/g, "\\|")}\` |`).join("\n");
  return out + "\n";
}

async function envMap() {
  const candidates = ["build.mjs", ...await filesUnder("src", (name) => name.endsWith(".js")), ...await filesUnder("scripts", (name) => name.endsWith(".mjs"))];
  const owners = new Map();
  for (const file of candidates) {
    const source = await fs.readFile(path.join(root, file), "utf8");
    for (const match of source.matchAll(/(?:process\.)?env\.([A-Z][A-Z0-9_]+)/g)) {
      if (!owners.has(match[1])) owners.set(match[1], new Set());
      owners.get(match[1]).add(file);
    }
  }
  let out = heading("Environment variables");
  out += "This is a usage inventory, not a promise that every variable is public configuration.\n\n";
  out += "| Variable | Read by |\n| --- | --- |\n";
  out += [...owners].sort(([a], [b]) => a.localeCompare(b))
    .map(([name, files]) => `| \`${name}\` | ${[...files].sort().map((file) => `\`${file}\``).join(", ")} |`).join("\n");
  return out + "\n";
}

function mcpToolMap() {
  let out = heading("MCP tools");
  for (const tool of toolDefinitions) {
    const summary = String(tool.description || "").split(/(?<=[.!?])\s/)[0];
    out += `## ${tool.name}\n\n${summary}\n\n`;
    const fields = Object.keys(tool.input || {});
    out += fields.length ? `Inputs: ${fields.map((field) => `\`${field}\``).join(", ")}\n\n` : "Inputs: none.\n\n";
  }
  return out;
}

function commandMap(scripts) {
  let out = heading("Commands");
  out += "| Command | Expansion |\n| --- | --- |\n";
  out += Object.entries(scripts).sort(([a], [b]) => a.localeCompare(b))
    .map(([name, command]) => `| \`npm run ${name}\` | \`${String(command).replace(/\|/g, "\\|")}\` |`).join("\n");
  return out + "\n";
}

function cspMap() {
  let out = heading("Network policy");
  out += "## Browser connect sources\n\n";
  out += WEB_CONNECT_SOURCES.map((source) => `- \`${source}\``).join("\n") + "\n\n";
  out += "The browser list is broad so users can choose custom model endpoints; script execution remains self-only.\n\n";
  out += "## Fetch-proxy hosts\n\n";
  out += FETCH_PROXY_ALLOWED_HOSTS.map((host) => `- \`${host}\``).join("\n") + "\n\n";
  out += "The proxy list is a separate server-side SSRF boundary and is intentionally narrow.\n";
  return out;
}

async function buildTour() {
  const [uiAssets, reducerExcerpt, engineExcerpt, bridgeExcerpt, snapshotExcerpt] = await Promise.all([
    getUiAssets(),
    excerpt("src/core/hole/reduce.js", "export function reduceHoleEvent", 22),
    excerpt("src/core/engine/hole-engine.js", "export class", 26),
    excerpt("src/node/bridge/agents/agent.js", "export", 24),
    excerpt("src/core/snapshot-html.js", "export function buildSnapshotHtml", 28),
  ]);
  const nodes = [
    tourNode("tour-root", null, "How Rabbithole works", 0, 0, `# How Rabbithole works

Rabbithole keeps one document graph and projects it into reading, canvas, live-agent, web-provider, and frozen forms.

\`\`\`mermaid
flowchart LR
  Ask[Question at a place] --> Reducer[One reducer]
  Reducer --> Hosts[Two hosts]
  Hosts --> Canvas[One interface]
  Canvas --> Snapshot[Offline snapshot]
\`\`\`

Open the neighboring cards to follow the architecture.`),
    tourNode("tour-reducer", "tour-root", "One reducer", 700, -450, `# One reducer

Every host sends the same event vocabulary through the same state transition. The reducer remains pure enough to run against a deep-frozen golden corpus in both server and browser runtimes.

\`\`\`js
${reducerExcerpt}
\`\`\``),
    tourNode("tour-hosts", "tour-root", "Two hosts, one engine", 700, 0, `# Two hosts, one engine

The local MCP session and browser-only provider host share the document engine. Their adapters retain only what genuinely differs: agent listening on one side and model generation on the other.

\`\`\`mermaid
flowchart TB
  MCP[MCP adapter] --> Engine[Hole engine]
  Web[Web adapter] --> Engine
  Engine --> Store[Store port]
  Engine --> UI[Browser event stream]
\`\`\`

\`\`\`js
${engineExcerpt}
\`\`\``),
    tourNode("tour-bridge", "tour-hosts", "Subscription bridge", 1400, -100, `# Subscription bridge

The optional loopback bridge lets the web host use a signed-in coding-agent subscription. Backend-specific process details sit behind one agent contract; authentication and origin policy remain at the HTTP boundary.

\`\`\`js
${bridgeExcerpt}
\`\`\``),
    tourNode("tour-snapshot", "tour-reducer", "Frozen snapshot pipeline", 1400, 450, `# Frozen snapshot pipeline

A snapshot is a privacy-filtered projection of the same graph, assembled with the shipped stylesheet, sanitizer, renderer, and frozen client. This file is itself that pipeline's output.

\`\`\`mermaid
flowchart LR
  Hole[Persisted hole] --> Project[Snapshot projection]
  Project --> Assemble[Self-contained HTML]
  Assemble --> Offline[Offline canvas]
\`\`\`

\`\`\`js
${snapshotExcerpt}
\`\`\``),
  ];
  const hole = toPersistedHole({
    hole_id: "architecture-tour",
    title: "How Rabbithole works",
    root_id: "tour-root",
    created_at: "2026-08-29T00:00:00.000Z",
    view_state: { mode: "canvas", node_id: "tour-root", scroll: 0, view: { x: 80, y: 70, scale: 0.62 } },
    nodes,
  }, { updatedAt: "2026-08-29T00:00:00.000Z" });
  const projection = createSnapshotProjection(hole, hole.view_state, {});
  return buildSnapshotHtml({
    title: hole.title,
    stylesheetText: uiAssets.stylesheetText,
    dompurifySource: getDompurifyScript(),
    mermaidSource: getMermaidScript(),
    frozenClientSource: uiAssets.frozenClientSource,
    snapshotProjection: projection,
  });
}

function tourNode(id, parentId, title, x, y, markdown) {
  return makeNode({
    id,
    parent_id: parentId,
    title,
    markdown,
    position: { x, y },
    size: { w: 560, h: 620 },
    status: "answered",
    read: true,
    created_at: "2026-08-29T00:00:00.000Z",
  });
}

async function excerpt(relativePath, marker, lines) {
  const source = await fs.readFile(path.join(root, relativePath), "utf8");
  const all = source.split("\n");
  const start = Math.max(0, all.findIndex((line) => line.includes(marker)));
  return all.slice(start, start + lines).join("\n").replace(/```/g, "` ` `");
}

async function readTestPurposes(files) {
  const result = [];
  const invalid = [];
  for (const file of files) {
    const source = await fs.readFile(path.join(root, file), "utf8");
    const match = source.match(/^\/\*\* @protects (.+?) \*\/\r?\n/);
    if (!match) invalid.push(file);
    else result.push({ file, purpose: match[1] });
  }
  if (invalid.length) throw new Error(`Tests missing an opening @protects docblock:\n${invalid.join("\n")}`);
  return result.sort((a, b) => a.file.localeCompare(b.file));
}

async function scanDocumentPaths() {
  const docs = ["README.md", "AGENTS.md", "CONTRIBUTING.md", ...await filesUnder("docs", (name) => name.endsWith(".md"))];
  const missing = [];
  for (const document of docs) {
    const source = await fs.readFile(path.join(root, document), "utf8");
    for (const candidate of documentedPaths(source)) {
      const normalized = candidate.replace(/^\.\//, "").replace(/:(?:L)?\d+(?:-\d+)?$/, "").replace(/[),.;:]$/, "");
      if (!normalized || normalized.includes("*") || normalized.includes("{") || normalized.includes("<")) continue;
      if (!await exists(path.resolve(root, normalized))) missing.push(`${document}: \`${candidate}\``);
    }
  }
  return [...new Set(missing)].sort();
}

function documentedPaths(source) {
  const known = /^(?:\.\.?\/|src\/|test\/|scripts\/|docs\/|dist\/|web\/|website\/|workers\/|bin\/|policy\/|\.github\/|package\.json(?:$|:)|README\.md(?:$|:)|AGENTS\.md(?:$|:)|CONTRIBUTING\.md(?:$|:)|LICENSE(?:$|:)|THIRD_PARTY_NOTICES\.md(?:$|:))/;
  const inline = [...source.matchAll(/`([^`\n]+)`/g)].map((match) => match[1].trim()).filter((value) => known.test(value));
  const code = [...source.matchAll(/(?:^|[\s"'(])((?:src|test|scripts|docs|dist|web|website|workers|bin|policy|\.github)\/[A-Za-z0-9_./-]+\.(?:js|mjs|md|json|css|html|toml|ya?ml))/gm)]
    .map((match) => match[1]);
  return [...inline, ...code];
}

async function filesUnder(relativeDirectory, predicate) {
  const base = path.join(root, relativeDirectory);
  const found = [];
  async function walk(directory) {
    for (const entry of await fs.readdir(directory, { withFileTypes: true })) {
      const full = path.join(directory, entry.name);
      if (entry.isDirectory()) await walk(full);
      else if (entry.isFile() && predicate(entry.name)) found.push(path.relative(root, full).split(path.sep).join("/"));
    }
  }
  await walk(base);
  return found.sort();
}

async function exists(target) {
  try { await fs.access(target); return true; } catch { return false; }
}
