/** @type {any} */
export const r = {
  lifecycle: null,
  CARD_COMPOSER_COPY: Object.freeze({
    frozen: "Read-only snapshot",
    closed: "Session ended — saved",
    pending: "Still being written…",
    away: "Asks are saved for the agent…",
    live: "Ask or note…",
  }),
  STANDALONE_COMPOSER_COPY: Object.freeze({
    frozen: "Read-only snapshot",
    closed: "Session ended",
    pending: "Ask or note…",
    away: "Ask or note…",
    live: "Ask or note…",
  }),
  filmCameraHandle: null,
  cardResizeObserver: null,
  activePointerGestures: new Set(),
  suppressClickUntil: 0,
  cardMenuController: null,
  cardMenuNode: null,
  pinnedWindows: null,
  COLLAPSED_STACK_GAP: 12,
  COLLAPSED_STACK_INDENT: 24,
  COLLAPSED_STACK_MAX_DEPTH: 3,
  NODE_EXPAND_ICON: "",
  NODE_COLLAPSE_ICON: "",
  NODE_MORE_ICON: "",
  NODE_RESTORE_ICON: "",
  edgeRaf: 0,
  edgeRedrawAll: false,
  edgeRedrawIds: {},
  edgePositionNodeIds: {},
  edgeEls: {},
  edgeGeometry: {},
  edgeHl: {},
  wheelKind: null,
  wheelCard: null,
  wheelTs: 0,
};
